# Generated by Django 4.0.5 on 2022-06-29 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='productos',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='crud.producto'),
        ),
    ]
