# Generated by Django 4.0.5 on 2022-06-29 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_carro_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='total',
            new_name='cantidad',
        ),
    ]
