# Generated by Django 4.0.5 on 2022-06-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_rename_total_carro_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
