# Generated by Django 4.0.5 on 2022-06-30 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_producto_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Stock',
            new_name='stock',
        ),
    ]
