# Generated by Django 4.0.5 on 2022-06-30 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_rename_stock_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipoTarjeta', models.CharField(max_length=100)),
                ('AporteMensual', models.CharField(max_length=100)),
                ('nTarjeta', models.CharField(max_length=20)),
                ('venc', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=20)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.usuario')),
            ],
        ),
    ]
