# Generated by Django 4.0.5 on 2022-06-30 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_subscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscripcion',
            name='tipoTarjeta',
        ),
        migrations.AddField(
            model_name='subscripcion',
            name='tipoPago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud.tipopago'),
            preserve_default=False,
        ),
    ]
