# Generated by Django 4.0.5 on 2022-06-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_remove_subscripcion_tipotarjeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscripcion',
            name='nTarjeta',
            field=models.CharField(max_length=16),
        ),
    ]
