# Generated by Django 4.0.5 on 2022-06-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_alter_subscripcion_ntarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscripcion',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
    ]
