# Generated by Django 4.1.3 on 2022-11-29 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud', '0010_alter_subscripcion_cvv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('nDocumento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.CreateModel(
            name='detalleDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.usuario')),
                ('id_usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.documento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tipopago')),
            ],
        ),
    ]
