# Generated by Django 4.1.3 on 2022-11-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_documento_servicio_remove_producto_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codBarra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
